[project]
name = "axium-backend"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.115.12",
    "pandas>=2.3.0",
    "scikit-learn>=1.7.0",
]
